services:
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: laravel_app
    env_file:
      - .env.docker
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks: [laravel_net]

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel_nginx
    ports:
      - '8888:80'
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks: [laravel_net]

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: ninepoint
      MYSQL_ROOT_PASSWORD: "Inimfonjonah2015@"
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    networks: [laravel_net]

volumes:
  db_data:

networks:
  laravel_net: {}
